language: ruby

bundler_args: --without debugger

cache: bundler
sudo: false

before_install:
  - gem --version

rvm:
  - 2.4.0
  - ruby-head
  
matrix:
  allow_failures:
    - rvm: ruby-head

notifications:
  email:
    recipients:
      - ngiger@ywesee.com
